[package]
name = "librius"
version = "0.1.0"
edition = "2024"
authors = ["Alessandro Maestri <umpire274@github.com>"]
description = "A personal library manager CLI written in Rust."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/umpire274/librius"
repository = "https://github.com/umpire274/rbackup"
keywords = ["books", "library", "cli", "sqlite", "manager"]
categories = ["command-line-utilities", "database", "data-structures", "productivity", "rust-patterns"]
exclude = [
    "target/*",
    ".idea/*",
    ".github/*",
    ".gitignore",
    "config/*",
    "*.sh",
    "*.bat",
]

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
chrono = "0.4.42"
sys-locale = "0.3.2"
globset = "0.4.16"
serde_yaml = "0.9.33"
dirs = "5.0"
rusqlite = { version = "0.31", features = ["bundled"] }
thiserror = "1.0"
colored = "2.1"

[profile.release]
opt-level = 3
